java:
  url: https://github.com/bell-sw/Liberica/tags
  regex: /tag/([0-9A-Za-z.\-_]+)
  bitnami: docker.io/bitnami/java
  bitnamisecure: docker.io/bitnamisecure/java-min
  cg: cgr.dev/chainguard/jdk
  version_commands:
    bitnami: "java --version"
    bitnamisecure: "java --version"
    cg: "javac --version"
