dotnet:
  url: https://github.com/dotnet/aspnetcore/tags
  regex: /tag/v([0-9\.]+[a-zA-Z0-9\-]*)
  bitnami:
    image: docker.io/bitnami/aspnet-core
    command: "dotnet --info"
    regex: "Version: *([0-9.]+)"
  bitnamisecure:
    image: docker.io/bitnamisecure/aspnet-min
    command: "--info"
    regex: "Version: *([0-9.]+)"
  cg:
    image: cgr.dev/chainguard/aspnet-runtime
    command: "--info"
    regex: "Version: *([0-9.]+)"

go:
  url: https://github.com/golang/go/tags
  regex: /tag/go([0-9\.]+[a-zA-Z0-9\-]*)
  bitnami:
    image: docker.io/bitnami/golang
    command: "go version"
    regex: "go version go([0-9.]+)"
  bitnamisecure:
    image: docker.io/bitnamisecure/golang
    command: "go version"
    regex: "go version go([0-9.]+)"
  cg:
    image: cgr.dev/chainguard/go
    command: "version"
    regex: "go version go([0-9.]+)"

gradle:
  url: https://github.com/gradle/gradle/tags
  regex: /tag/v([0-9\.]+[a-zA-Z0-9\-]*)
  bitnami:
    image: docker.io/bitnami/gradle
    command: "gradle --version"
    regex: "Gradle ([0-9.]+)"
  bitnamisecure:
    image: docker.io/bitnamisecure/gradle
    command: "gradle --version"
    regex: "Gradle ([0-9.]+)"
  cg:
    image: cgr.dev/chainguard/gradle
    command: "--version"
    regex: "Gradle ([0-9.]+)"

java:
  url: https://github.com/bell-sw/Liberica/tags
  regex: /tag/([0-9A-Za-z.\-_]+)
  bitnami:
    image: docker.io/bitnami/java
    command: "java --version"
    regex: "openjdk ([0-9.]+)"
  bitnamisecure:
    image: docker.io/bitnamisecure/java-min
    command: ""
    regex: ""
  cg:
    image:  cgr.dev/chainguard/jdk
    command: "javac --version"
    regex: "javac ([0-9.]+)"

node:
  url: https://github.com/nodejs/node/tags
  regex: /tag/v([0-9][02468].[0-9\\.]+)
  bitnami:
    image: docker.io/bitnami/node
    command: "node --version"
    regex: "v([0-9.]+)"
  bitnamisecure:
    image: docker.io/bitnamisecure/node-min
    command: "--version"
    regex: "v([0-9.]+)"
  cg:
    image: cgr.dev/chainguard/node
    command: "--version"
    regex: "v([0-9.]+)"

php:
  url: https://github.com/php/php-src/tags
  regex: /tag/php-([0-9\.]+[a-zA-Z0-9\-]*)
  bitnami:
    image: docker.io/bitnami/php-fpm
    command: "php --version"
    regex: "PHP ([0-9.]+)"
  bitnamisecure:
    image: docker.io/bitnamisecure/php-fpm-min
    command: ""
    regex: ""
  cg:
    image: cgr.dev/chainguard/php:latest-fpm
    command: ""
    regex: ""

python:
  url: https://github.com/python/cpython/tags
  regex: /tag/v([0-9\.]+[a-zA-Z0-9\-]*)
  bitnami:
    image: docker.io/bitnami/python
    command: "python --version"
    regex: "Python ([0-9.]+)"
  bitnamisecure:
    image: docker.io/bitnamisecure/python-min
    command: "--version"
    regex: "Python ([0-9.]+)"
  cg:
    image: cgr.dev/chainguard/python
    command: "--version"
    regex: "Python ([0-9.]+)"

ruby:
  url: https://github.com/ruby/ruby/tags
  regex: /tag/v([0-9_]+)
  bitnami:
    image: docker.io/bitnami/ruby
    command: "ruby --version"
    regex: "ruby ([0-9.]+)"
  bitnamisecure:
    image: docker.io/bitnamisecure/ruby-min
    command: "--version"
    regex: "ruby ([0-9.]+)"
  cg:
    image: cgr.dev/chainguard/ruby
    command: "--version"
    regex: "ruby ([0-9.]+)"

rust:
  url: https://github.com/rust-lang/rust/tags
  regex: /tag/([0-9\.]+[a-zA-Z0-9\-]*)
  bitnami:
    image: docker.io/bitnami/rust
    command: "rustc --version"
    regex: "rustc ([0-9.]+)"
  bitnamisecure:
    image: docker.io/bitnamisecure/rust
    command: "rustc --version"
    regex: "rustc ([0-9.]+)"
  cg:
    image: cgr.dev/chainguard/rust
    command: "--version"
    regex: "rustc ([0-9.]+)"

tomcat:
  url: https://github.com/apache/tomcat/tags
  regex: /tag/(10\.[0-9\.]+[a-zA-Z0-9\-]*)
  bitnami:
    image: docker.io/bitnami/tomcat
    command: "catalina.sh version"
    regex: "Server version: Apache Tomcat/([0-9.]+)"
  bitnamisecure:
    image: docker.io/bitnamisecure/tomcat
    command: "catalina.sh version"
    regex: "Server version: Apache Tomcat/([0-9.]+)"
  cg:
    image: cgr.dev/chainguard/tomcat
    command: "version"
    regex: "Server version: Apache Tomcat/([0-9.]+)"